spring:
#  热部署相关
  devtools:
    add-properties: true
    restart:
      enabled: true
    livereload:
      enabled: true
  application:
    name: VOID-SPRING | 春野
#    模板引擎
  freemarker:
    charset: UTF-8
    template-loader-path: classpath:/templates/
    suffix: .ftlh
    cache: false
    prefer-file-system-access: false
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    allow-request-override: false
    request-context-attribute: request
    settings:
      template_update_delay: 0
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  banner:
    location: META-INF/resources/banner.txt
#    数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  data:
    redis:
      repositories:
        enabled: false
#    ORM
mybatis-plus:
  global-config:
    banner: false
#    文档相关
knife4j:
  enable: true
  setting:
    enableDebug: true
    swaggerModelName: 实体类列表
