spring:
  banner:
    location: META-INF/resources/banner.txt
  devtools:
    add-properties: false
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  global-config:
    banner: false