#详细配置 https://baomidou.com/pages/56bac0/#configuration
mybatis-plus:
  configuration:
#   数据库字段映射策略
    mapUnderscoreToCamelCase: true
    auto-mapping-behavior: PARTIAL
    auto-mapping-unknown-column-behavior: WARNING
#   单体服务可以开启一级缓存，微服务架构需要关闭缓存
    localCacheScope: SESSION
#   二级缓存开启
    cacheEnabled: true
#   查询结果为null时，是否调用类的setter方法
    callSettersOnNulls: false
  global-config:
    db-config:
#     默认ID策略
      id-type: ASSIGN_UUID
      logicDeleteField: status
      logic-not-delete-value: 0
      logic-delete-value: 1
#     表名前缀
      table-prefix: ${void.global-orm-config.table-prefix}
