server:
  port: 10000
spring:
  datasource:
    url: jdbc:mysql:///VOID?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  application:
    name: VOID-SPRING
  profiles:
    active: dev
    include: []
void:
  doc:
    base-package: cn.toutatis
