server:
  port: ${PORT:10000}
# SpringBoot 优雅停机 http://events.jianshu.io/p/199e419c025e
  shutdown: graceful
spring:
  application:
    name: VOID-SPRING
  profiles:
    active: dev
    include: ["void","datasource","jpa","mybatis"]
  lifecycle:
    timeout-per-shutdown-phase: 30s