spring:
  devtools:
    add-properties: false
    restart:
      enabled: false
    livereload:
      enabled: false
  application:
    name: VOID-SPRING | 春野
  freemarker:
    charset: UTF-8
    template-loader-path: classpath:/templates/
    suffix: .ftlh
    cache: true
    prefer-file-system-access: false
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    allow-request-override: false
    request-context-attribute: request
    settings:
      template_update_delay: 0
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    throw-exception-if-no-handler-found: true
  banner:
    location: META-INF/resources/banner.txt
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      repositories:
        enabled: false
mybatis-plus:
  global-config:
    banner: false
knife4j:
  enable: true
  setting:
    enableDebug: true
    swaggerModelName: 实体类列表
    enableVersion: true
  data:
    redis:
      repositories:
        enabled: false
springdoc:
  model-and-view-allowed: true
  swagger-ui:
    try-it-out-enabled: true
    display-request-duration: true
  show-login-endpoint: true
  remove-broken-reference-definitions: false
datasource:
  protocol: jdbc:mysql://
