spring:
#  热部署相关
  devtools:
    add-properties: true
    restart:
      enabled: true
    livereload:
      enabled: true
  application:
    name: VOID-SPRING | 春野
#    模板引擎
  freemarker:
    charset: UTF-8
    template-loader-path: classpath:/templates/
    suffix: .ftlh
    cache: false
    prefer-file-system-access: false
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    allow-request-override: false
    request-context-attribute: request
    settings:
      template_update_delay: 0
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  banner:
    location: META-INF/resources/banner.txt
#    数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  data:
    redis:
      repositories:
        enabled: false
#    ORM
mybatis-plus:
  global-config:
    banner: false
#    文档相关
knife4j:
  enable: true
  setting:
    enable-debug: true
    swagger-model-name: 实体类列表
    enable-version: true
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: "Apache License 2.0 | Copyright  2020-[XVOID]-[Toutatis_Gc](https://github.com/ToutatisGc)"
springdoc:
  model-and-view-allowed: true
  swagger-ui:
    try-it-out-enabled: true
    display-request-duration: true
#  show-actuator: true
datasource:
  protocol: jdbc:p6spy:mysql://

