# 定时任务配置
spring:
  quartz:
    auto-startup: true
    job-store-type: JDBC
    wait-for-jobs-to-complete-on-shutdown: true
    jdbc:
      # FIXME 开发和测试环境下可以总是生成数据库表,但注意线上生产
      initialize-schema: ALWAYS
    scheduler-name: XVOID-QUARTZ-SCHEDULER