spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
#    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: cn.toutatis.xvoid.support.spring.config.orm.jpa.VoidNamingStrategyStandardImpl
    open-in-view: true
#   hibernate的dialect指定可能并不准确，可以使用手动指定选择方言
    database-platform: org.hibernate.dialect.MariaDB10Dialect