server:
  port: ${PORT:20080}
# SpringBoot 优雅停机 http://events.jianshu.io/p/199e419c025e
  shutdown: GRACEFUL
  tomcat:
    keep-alive-timeout: 10s
spring:
  application:
    name: VOID-SPRING | 春野
  profiles:
    active: produce
    include: ["void","datasource","jpa","mybatis","third","ampq"]
  lifecycle:
    timeout-per-shutdown-phase: 30s
  session:
    store-type: REDIS
  rabbitmq:
    host: "localhost"
    port: 5672
    template:
      retry:
        enabled: true
        initial-interval: 1000ms