void:
  mode: DEV
  global-log-config:
    record-request: true
    record-request-params: true
    record-to-db: true
    record-static-resource: false
  global-orm-config:
    use-table-prefix: false
    table-prefix: vb_
  doc-config:
    description: VOID 文档接口
    base-package: cn.toutatis
    title: VOID文档
  global-service-config:
    auto-config: true
    use-detailed-mode: true
    compress-file: true
    file-object-classify: true